spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mariadb:replication://localhost:33306,localhost:33307/TechieNotes
    username: root
    password: masterghost
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000
      key-prefix: dev-
logging:
  level:
    root: INFO
    org:
      hibernate: INFO
      hibernate.SQL: DEBUG
      hibernate.cache: DEBUG
      hibernate.stat: DEBUG
      hibernate.type.descriptor.sql: TRACE